2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_setup.py:_flush():67] Configure stats pid to 2970839
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_setup.py:_flush():67] Loading settings from /home/peng/.config/wandb/settings
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_setup.py:_flush():67] Loading settings from /home/peng/code/CFDiff/wandb/settings
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/peng/code/CFDiff/wandb/run-20250320_172106-965m4atn/logs/debug.log
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/peng/code/CFDiff/wandb/run-20250320_172106-965m4atn/logs/debug-internal.log
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_init.py:init():761] calling init triggers
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10, '_wandb': {}}
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_init.py:init():784] starting backend
2025-03-20 17:21:06,100 INFO    MainThread:2970839 [wandb_init.py:init():788] sending inform_init request
2025-03-20 17:21:06,104 INFO    MainThread:2970839 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-20 17:21:06,104 INFO    MainThread:2970839 [wandb_init.py:init():798] backend started and connected
2025-03-20 17:21:06,104 INFO    MainThread:2970839 [wandb_init.py:init():891] updated telemetry
2025-03-20 17:21:06,107 INFO    MainThread:2970839 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-20 17:21:07,959 ERROR   MainThread:2970839 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/peng/anaconda3/envs/wsss/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peng/anaconda3/envs/wsss/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404: {"data":{"upsertBucket":null},"errors":[{"message":"entity my-awesome-team-name not found during upsertBucket","path":["upsertBucket"]}]}
2025-03-20 17:21:08,960 INFO    MsgRouterThr:2970839 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
